server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;

    types {
        application/javascript mjs;
        font/ttf ttf;
        font/otf otf;
        font/woff woff;
        font/woff2 woff2;
    }
    
    location / {
        try_files $uri $uri/ /index.html;
    }
}